name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      run: |
        sudo apt install rlwrap
        mkdir -p ~/bin ~/roms
        echo ~/bin >> $GITHUB_PATH      

    - name: Install UXN
      run: |
        cd ~
        git clone https://git.sr.ht/~rabbits/uxn11
        cd uxn11
        make
        make install
    
    - name: Build Merlin OS
      run: |
        make
        make install

    - name: Run Merlin OS
      run: echo | merlin

    - name: Release Merlin OS
      uses: actions/upload-artifact@v4.3.4
      with:
        name: merlin.rom
        path: rom/merlin.rom
          
