name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Merlin OS
      run: make

    - name: Run Merlin OS
      run: echo | etc/uxncli rom/merlin.rom

    - name: Release Merlin OS
      uses: actions/upload-artifact@v4.3.4
      with:
        name: merlin.rom
        path: rom/merlin.rom
          
